### ISSUE TITLE
Ruby file descriptors seem to be leaking

### ISSUE THREAD

**Issue by neongreen** [aelve/codesearch#108]
Steps to reproduce:

1. `make download-ruby`, wait a bit and kill
2. `make index-ruby`
3. `make serve` to start the server
4. search for something on `/ruby` (e.g. `test`)
5. look at the number of open files: `lsof | grep data/gem | wc -l`

In my case I have 10693 Ruby files in the index and 12383 open Ruby files.

**Comment by kamilongus** [comment]
@ppressives found a solution to bug. I pass the task to him.
