### ISSUE TITLE
Add a regex testsuite for roundtrip-only tests

### ISSUE THREAD

**Issue by neongreen** [aelve/codesearch#151]
I.e. there are some long regexes where we don't care what they parse into, but at least we can check that we don't violate the roundtrip property. We can steal regexes from here:

* https://golang.org/src/regexp/testdata/re2-search.txt
* http://hg.openjdk.java.net/jdk7u/jdk7u6/jdk/file/8c2c5d63a17e/test/java/util/regex/TestCases.txt
* https://github.com/dlang/phobos/blob/master/std/regex/internal/tests.d
* https://www.perlmonks.org/bare/?node_id=558868

**Comment by Evengining** [comment]
I will check everything, but only after I finish my task!
