### ISSUE TITLE
Plus signs disappear when going to the second page of results

### ISSUE THREAD

**Issue by neongreen** [aelve/codesearch#186]
1. Go to https://codesearch.aelve.com/haskell
2. Search for `a+b`
3. Go to the second page
4. The regex will change to `a b`

**Comment by Kabowyad** [comment]
@neongreen I repeated and got `a b?filter=`, btw it's still not working, but in other way. Gonna figure out problem.

**Comment by Evengining** [comment]
I'm fixing it here йhttps://github.com/aelve/codesearch/pull/183
