### ISSUE TITLE
"?filter=" gets appended to the query when going to the second page of results

### ISSUE THREAD

**Issue by neongreen** [aelve/codesearch#190]
Search for "module": https://codesearch.aelve.com/haskell/search?query=module&filter=&sources=on

![image](https://user-images.githubusercontent.com/1523306/50801331-4fd58380-1338-11e9-8690-991046d1808a.png)

Go to the second page: https://codesearch.aelve.com/haskell/search?query=module?filter=&caseInsensitive=&spaceInsensitive=&precise=&sources=on&page=2

![image](https://user-images.githubusercontent.com/1523306/50801369-7b586e00-1338-11e9-9c47-a1d807cc846f.png)

**Comment by Evengining** [comment]
@neongreen I almost accidentally fixed this bug in #192. Perhaps this is no longer relevant.
