### ISSUE TITLE
Do not pass a lot of parameters to cindex. Use append to existing index.

### ISSUE THREAD

**Issue by kamilongus** [aelve/codesearch#207]
![image](https://user-images.githubusercontent.com/5605372/52167921-2ee82e80-273c-11e9-8182-b7d4cba7a9cb.png)

**Comment by neongreen** [comment]
This doesn't affect Rust and Haskell, right?

**Comment by Kabowyad** [comment]
@kamilongus I just tested on the fresh develop and everything works fine.

**Comment by kamilongus** [comment]
[Note]
`getconf ARG_MAX` returns is not number of arguments, but the maximum length of the buffer of arguments.

**Comment by kamilongus** [comment]
Append to existing index is very slow. For example an index for gems packages already running in 41 minutes with batch size equal to 10 000.
