### ISSUE TITLE
Pages are counted incorrectly

### ISSUE THREAD

**Issue by neongreen** [aelve/codesearch#252]
Search for `{-@ LIQUID` in precise mode: <https://codesearch.aelve.com/haskell/search?query={-%40%20LIQUID&insensitive=off&space=off&precise=on&sources=on>

There are six pages of results. However, you can change the page number in the URL and get more results: <https://codesearch.aelve.com/haskell/search?query={-@+LIQUID&insensitive=off&space=off&precise=on&sources=on&page=10>

**Comment by kamilongus** [comment]
This issue has already been fixed on staging server: https://staging.codesearch.aelve.com/haskell/search?query=%7B-@+LIQUID&insensitive=off&space=off&precise=on&sources=on&page=6
