### ISSUE TITLE
Sort packages by number of downloads / popularity

### ISSUE THREAD

**Issue by neongreen** [aelve/codesearch#39]
(the page should also mention that they are sorted by popularity, somewhere)

**Comment by Kabowyad** [comment]
But who we will determine the quantity of downloads?
E.g. in haskell, ruby and javascript there are number of download on site of package.
But in rust not.
The first idea - i can create the parser which will go for web-site of package and crawl the quantity of downloads.

**Comment by neongreen** [comment]
Let's not start this issue just yet.

Parsing the site: usually a bad idea. First we should research whether we can get the number of downloads via API (e.g. for Hackage we can, I think).
Crates.io also gives access to the download counts via its API, see https://github.com/rust-lang/crates.io/blob/master/src/router.rs#L57-L60.
Finally, number of downloads isn't the only thing we should take into account. For instance, we can also look at the number of packages that have the given package as a dependency (and we have that info even without any API).
However, things like migration to Zoekt are more important right now.

**Comment by neongreen** [comment]
https://www.notion.so/aelve/Sort-packages-by-number-of-downloads-popularity-2adeba706bda473094514be45f7bb5fb
