### ISSUE TITLE
Add RubyGems.org

### ISSUE THREAD

**Issue by neongreen** [aelve/codesearch#54]
There's a tool for mirroring here: https://github.com/rubygems/rubygems-mirror. It mirrors everything, not just the latest versions, so it's unusable on its own. It can either be modified, or used for inspiration :slightly_smiling_face: 

The index lives at http://rubygems.org/specs.4.8.gz. It's serialized using [some Ruby thing](http://ruby-doc.org/core-2.2.2/Marshal.html).

The subtasks are:

* [x] Learn how to deserialize the index.
* [x] Figure out what extensions to keep.
* [x] Download the data.
* [x] Make a /ruby page with the right libs, title, etc.

**Comment by neongreen** [comment]
The subtasks are:

* [ ] Learn how to deserialize the index.
* [ ] Figure out what extensions to keep.
* [ ] Download the data.
* [ ] Make a /ruby page with the right libs, title, etc.

**Comment by vlad107** [comment]
https://robots.thoughtbot.com/fetching-source-index-for-http-rubygems-org
