### ISSUE TITLE
Fix index update for JavaScript

### ISSUE THREAD

**Issue by neongreen** [aelve/codesearch#55]

**Comment by kamilongus** [comment]
[Note]
Couchdb is very slow db. 
For example query: https://replicate.npmjs.com/_all_docs?limit=10&skip=784100 can return following result:
![image](https://user-images.githubusercontent.com/5605372/45382630-49512c80-b622-11e8-8a50-457ae4c0d725.png)
Nice.

**Comment by neongreen** [comment]
@kamilongus stop killing their CouchDB! :slightly_smiling_face:

> The skip parameter can be used along with the limit parameter to implement pagination. However, skipping a large number of rows can be inefficient. Instead, set the skip parameter’s value to 1 and use the key of the last row on the previous page as the startkey (endkey if output is reversed) parameter, and the document ID of the last row on the previous page as the startkey_docid (endkey_docid if output is reversed) parameter. This should give you better performance since CouchDB will not need to scan the entire range of skipped rows."

**Comment by kamilongus** [comment]
@neongreen 
Yes, I also found this.
