### ISSUE TITLE
Ruby paths are weird

### ISSUE THREAD

**Issue by neongreen** [aelve/codesearch#66]
https://codesearch.aelve.com/ruby/search?query=blah&sources=on

`0.5.0.2/0.5.0.2/0.5.0.2/spec/castronaut/configuration_spec.rb`

**Comment by vlad107** [comment]
These paths are meaningless now. Will be fixed after implementing https://github.com/aelve/codesearch/issues/69

**Comment by neongreen** [comment]
I guess this is fixed now, I'll check tomorrow.

**Comment by neongreen** [comment]
I can confirm that this is fixed.
