### ISSUE TITLE
Serve source files from the server

### ISSUE THREAD

**Issue by neongreen** [aelve/codesearch#69]
* [x] Links should point to our server
* [x] Source should be highlighted
* [x] All matches should be highlighted
* [x] The link should jump to the right line (i.e. the line of the first match for the snippet)

**Comment by vlad107** [comment]
I suggest to split that task into at least two different subtasks:
1. The design of serving requests for a code
2. The view of displaying

**Comment by Som3** [comment]
We can use for source highlighting https://highlightjs.org/

**Comment by neongreen** [comment]
We already use Prism (look, the code snippets in search results are highlighted)

**Comment by Som3** [comment]
it's a little bit strange library
![image](https://user-images.githubusercontent.com/5718120/44686556-50d7d980-aa57-11e8-96b8-3e36c9bf4932.png)

**Comment by Som3** [comment]
Ok, u are right
