### ISSUE TITLE
Versioned CSS

### ISSUE THREAD

**Issue by neongreen** [aelve/codesearch#70]
I changed CSS and the header broke after a deploy:

![image](https://user-images.githubusercontent.com/1523306/43993168-b94dc694-9d89-11e8-8c78-10505e4147d4.png)

After Ctrl+Shift+R (or Cmd+Shift+E on macOS) the browser refreshed CSS and the header became normal:

![image](https://user-images.githubusercontent.com/1523306/43993176-d3a8f284-9d89-11e8-940a-caad5bab5496.png)

However, we can't expect users to do a hard reload every time we change our CSS substantially. Can we do something to fix it?

**Comment by kamilongus** [comment]
There are similar ways to solve:
1. Add some unique hash to css file name;
2. Add new revision number to css file. 

For example: 
1. `styles-5e8h0a.css` => `styles-5e8h1a.css`
2. `styles.css?version=3` => `styles.css?version=4`

Webpack use first way.

**Comment by neongreen** [comment]
Hm, the first one seems nicer. Does Play have something built-in for this?
