### ISSUE TITLE
Path should depend on the package name

### ISSUE THREAD

**Issue by kamilongus** [aelve/codesearch#74]
For example: `data/hackage/packet/x`

**Comment by neongreen** [comment]
I would also propose to remove duplication re/ versions and names. For instance, for Hackage:

```
we have: data/packages/foo/0.1/foo-0.1/...
we want: data/hackage/foo/0.1/...
```

**Comment by kamilongus** [comment]
@neongreen 
Archive and unzipped files store in same dir?

**Comment by neongreen** [comment]
Do we need archives for anything? I think we don't

**Comment by kamilongus** [comment]
> I would also propose to remove duplication re/ versions and names.
Duplicates are due to the storage of archives. If archives are useless, we can get rid of duplicate directories.

**Comment by neongreen** [comment]
Well, we can remove them even if the archives are still there – just move the files after unarchiving
