### ISSUE TITLE
Overhaul file filtering

### ISSUE THREAD

**Issue by neongreen** [aelve/codesearch#93]
This was discussed with @kamilongus. The idea is to create a single function that would do file filtering for all languages. For instance:

* we don't want files larger than 1MB
* we don't want files that are neither in Haskell/Rust/etc extension sets, nor in some predefined set of text file extensions (.json, .cabal, .md, etc)

Then we can do filtering in a uniform way. NB: and don't forget to change the NPM extension set, currently it contains some extra entries.

**Comment by kamilongus** [comment]
@neongreen 
> we don't want files larger than 1MB

Now we storing files with only allowed extensions.
For example: if any file with allowed extension have size larger then 1 MB -> remove it? 
I'm not sure if it's worth doing.

**Comment by neongreen** [comment]
I'm pretty sure that there are npmjs packages that include multi-megabyte .txt log files or something
